### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [neggles/middleflare#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
the import "github.com/neggles/traefik-cloudflare" must be related to the module name "github.com/neggles/middleflare"
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by neggles** [comment]
You're right, bot, and you should say it, but I have fixed this just now I think, so...
